name: Auto Assign requirements

permissions:
  issues: write
  contents: read
  pull-requests: write

on:
  issues:
    types: [opened]

env:
  MY_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  assign:
    name: Assign milestone to new issue
    runs-on: ubuntu-latest
    steps:
      - name: Assign issue to milestone
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            try {
              const issueNumber = context.payload.issue.number;
              const owner = context.repo.owner;
              const repo = context.repo.repo;

              const milestoneNumber = 1;

              console.log(`Assigning milestone ${milestoneNumber} to issue #${issueNumber}`);

              await github.rest.issues.update({
                owner,
                repo,
                issue_number: issueNumber,
                milestone: milestoneNumber
              });

              console.log('Milestone assigned successfully.');

            } catch (error) {
              core.setFailed(error.message);
              console.error(error);
            }
