name: Auto Assign requirements

permissions:
  issues: write
  contents: read
  pull-requests: write

on:
  issues:
    types: [opened]

jobs:
  assign:
    runs-on: ubuntu-latest
    steps:
      - name: Assign issue to project and milestone
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            try {
              const owner = context.repo.owner;

              const milestoneNumber = 1;

              await github.rest.issues.update({
                owner,
                issue_number: issueNumber,
                milestone: milestoneNumber
              });

            } catch (error) {
              core.setFailed(error.message);
              console.error(error);
            }

